name: ETL Pipeline

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "job1"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "job2"
  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "job3"
  job4:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "job4"
  job5:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "job5"
  job6:
    needs: job4, job5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "job6"

    

 