name: pipeline1

on:
  push:
    branches:
      - main

jobs:
  run-python-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Print Python version
        run: python --version

      - name: Run Python program
        run: python welcome.py
